AWSTemplateFormatVersion: '2010-09-09'
Description: "Generic CF Template to deploy an app via CodeCommit"

Parameters:
  CodeCommitHttpsUrl:
    Type: String
    Description: The Https url of a code commit repository
  ProjectName:
    Type: String
    Description: Name of the project
    Default: CodeBuildProject
  ProjectDescription:
    Type: String
    Description: General description of the project
    Default: CodeBuild Project

Resources:  
  
  rIamBuildProjectSourceRole:
    Description: TBI
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'logs:*'
                Effect: Allow
                Resource: '*' 
               
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Description: !Ref ProjectDescription
      ServiceRole: !Ref rIamBuildProjectSourceRole
      Artifacts:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-artifacts.html
        Type: NO_ARTIFACTS
      Environment: 
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          -
            Name: TEST_ENV_VARIABLE
            Value: PlaceHolder
      Source:
        Type: CODECOMMIT
        Location: !Ref CodeCommitHttpsUrl


               
  
