AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic Fargate Service'

Parameters:
  TemplateServiceName:
    Description: 'Unique Name for this service, can be anything.'
    Type: String

  ClusterArn:
    Description: 'The Arn of the cluster to deploy this service to'
    Type: String

  TaskDefinitionArn:
    Description: 'The family and revision (family:revision) or full ARN of the task definition to run in your service. The revision is required in order for the resource to stabilize.'
    Type: String

  TargetGroupArn:
    Description: 'The Arn of the target group to connect to'
    Type: String

  ContainerDefinitionName:
    Description: 'The name of the container definition for the load balancer to use, its the name property of the container definition'
    Type: String

  ContainerPort:
    Description: 'The ports that the containers need'
    Type: Number
    Default: 80

  TemplateVPC:
    Description: 'VPC to use'
    Type: AWS::EC2::VPC::Id

  SubnetA:
    Description: 'First Subnet'
    Type: AWS::EC2::Subnet::Id

  SubnetB:
    Description: 'Second Subnet'
    Type: AWS::EC2::Subnet::Id


Resources:
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ContainerSecurityGroup
      VpcId: !Ref TemplateVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 0.0.0.0/0
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref TemplateServiceName
      Cluster: !Ref ClusterArn
      TaskDefinition: !Ref TaskDefinitionArn
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 30 # This may need to be adjusted if the container takes a while to start up
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED # change to DISABLED if you're using private subnets that have access to a NAT gateway
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref ContainerDefinitionName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupArn





