---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic EC2 Instance'
Parameters:
  VpcId:
    Description: Vpc to Attach instance.
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: Subnet to Attach instance.
    Type: AWS::EC2::Subnet::Id

  SSHKeyName:
    Description: EC2 instance type
    ConstraintDescription: Please choose a valid KeyName
    Type: AWS::EC2::KeyPair::KeyName
    
  ImageId:
    Description: 'The AMI image Id for your region.'
    Type: AWS::EC2::Image::Id
    
  InstanceType:
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, m3.medium, m3.large,
      m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
      c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
      r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
    ConstraintDescription: Please choose a valid instance type.
    Type: String

  VolumeSize:
    Description: size of volume
    Type: Number
    Default: 50
    ConstraintDescription: Please choose a valid Number
    AllowedValues: [20, 50, 100, 200]
    
  IOPS:
    Description: total ipos
    Type: Number
    Default: 100
    ConstraintDescription: Please choose a valid Number
    AllowedValues: [100, 200, 500, 1000]
    
Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allow ssh
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      SubnetId: !Ref SubnetId
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref SSHKeyName
      SecurityGroupIds:
        - !GetAtt InstanceSecurityGroup.GroupId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: io1
            Iops: !Ref IOPS
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSize
          
          
